### ISSUE TITLE
Compatibility with PHP 7.4

### ISSUE THREAD

**Issue by sebastianbergmann** [zetacomponents/ConsoleTools#11]
PHP Deprecated:  Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in [src/input.php on line 535](https://github.com/zetacomponents/ConsoleTools/blob/master/src/input.php#L535)

**Comment by derickr** [comment]
This curious. When I run the tests with PHPUnit (the configured 5.7.27, or 7.5.18), code coverage shows that that line is covered, but I am not getting that deprecation warning shown. Why would that be?

**Comment by derickr** [comment]
ping @sebastianbergmann

**Comment by sebastianbergmann** [comment]
I ran into this while using [PHPAB](https://github.com/theseer/Autoload/issues/91). I do not care enough to debug this, sorry. Feel free to close this issue if you cannot reproduce it.

**Comment by derickr** [comment]
I don't care too much, but, I can now reproduce it. Sometimes I'd wish PHPUnit set `error_reporting=-1` by default :-)
