### ISSUE TITLE
CI: move to GH Actions ?

### ISSUE THREAD

**Issue by jrfnl** [zetacomponents/ConsoleTools#14]
Just noticed that this repo is still on Travis.

Is that intentional ? Or should the CI of this repo be converted to GH Actions ?

I'll happily send in a PR if so desired.

**Comment by derickr** [comment]
Starting with the easy one... This package, and all the other Zeta Components are still on Travis CI, only due to inaction on my part.
I'd be more than happy with a PR on moving this to GHA, which then can also serve as a template for the others that are currently on Travis CI.

**Comment by jrfnl** [comment]
See PR #17 ;-)
